### ISSUE TITLE
alien light (81) and force field (192) issues.

### ISSUE THREAD

**Issue by Infernus444** [zexlr8er/Wazzal_II#82] opened 2016-04-02 11:11 UTC
Those two objects (Alien light is a much, much bigger issue than force field) cause a very long freeze on low end PCs after a very short game time. Some other maps also use alien light and also freezes the game, but after much more time has passed (Since there are only few on them)

Simply wait for 2 minutes and enter the ZOO planet and those plot objects will load more than enough times to freeze the game for solid 30~ seconds (Mostly the light stacking). For high end computers which can handle it, place the alien light plot object near landing pad where you land. When you enter the planet, you will notice a big glob of green color due to how many times the light stacked on itself.

The solution for alien lights is to use an object definition and light (F6)  with high pulse speed applied over it in map editor. 

EDIT: Sorry, forgot that there was another issue related to it already open :I

**Comment by Infernus444** [comment] 2016-04-02 21:42
Just tested it. After extended gameplay, 3 maps that previously used alien light (Haven't been on Zoo planet yet) load immediately on entering on my potato powered PC. Force field (192) might have to do nothing with this freeze.

**Comment by zexlr8er** [comment] 2016-04-03 01:30
Duplicate of #58, and possibly related to #77. Should be largely resolved in new Steam version of Notrium!

**Closed as completed** 2016-04-08 15:26 UTC
Labels: notrium bug, duplicate, major
