### ISSUE TITLE
Overburden Notrium bug

### ISSUE THREAD

**Issue by Infernus444** [zexlr8er/Wazzal_II#86] opened 2016-04-02 21:16 UTC
Go to one of the planets, and take as much equipment as you can, but make sure you can, you will get slowed down by it. Leave the planet and enter the bridge. Sell or drop some items to get under the maximum weight value and expect to be as fast as before, but the slowdown is still there.

The Speed is fixed by saving and loading. May be fixed in Special Edition, as I only tested on Freeware version

**Comment by zexlr8er** [comment] 2016-04-03 01:28
Duplicate of #73, should be resolved in Steam version of Notrium (highly recommended).

**Closed as completed** 2016-04-08 15:26 UTC
Labels: notrium bug, duplicate, major
